require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
